In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/pakistan_household_electricity.csv")

In [3]:
df.head()

,date,city,temperature_c,humidity_percent,electricity_units_kwh,household_size,income_level,power_outage_hours
0,2022-01-01,Peshawar,26.9,88,26.65,3,Low,3.32
1,2022-01-02,Quetta,31.4,85,25.32,3,High,1.26
2,2022-01-03,Islamabad,37.5,51,23.40,7,Low,2.51
3,2022-01-04,Quetta,22.8,65,20.51,4,High,2.47
4,2022-01-05,Quetta,30.9,63,29.20,7,Middle,0.32

In [4]:
df.describe()

,temperature_c,humidity_percent,electricity_units_kwh,household_size,power_outage_hours
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,30.261533,60.402000,21.785600,4.976000,1.525673
std,6.934648,17.380001,6.041309,2.022412,1.530639
min,8.900000,30.000000,3.950000,2.000000,0.000000
25%,25.600000,45.000000,17.597500,3.000000,0.460000
50%,30.200000,60.500000,21.905000,5.000000,1.080000
75%,34.900000,76.000000,25.880000,7.000000,2.130000
max,52.400000,89.000000,41.460000,8.000000,12.390000

In [5]:
df.shape

(1500, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1500 non-null   object
 1   city                   1500 non-null   object
 2   temperature_c          1500 non-null   float64
 3   humidity_percent       1500 non-null   int64
 4   electricity_units_kwh  1500 non-null   float64
 5   household_size         1500 non-null   int64
 6   income_level           1500 non-null   object
 7   power_outage_hours     1500 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 93.9+ KB

In [7]:
df['date'] = pd.to_datetime(df['date'])

In [8]:
df.head(4)

,date,city,temperature_c,humidity_percent,electricity_units_kwh,household_size,income_level,power_outage_hours
0,2022-01-01,Peshawar,26.9,88,26.65,3,Low,3.32
1,2022-01-02,Quetta,31.4,85,25.32,3,High,1.26
2,2022-01-03,Islamabad,37.5,51,23.40,7,Low,2.51
3,2022-01-04,Quetta,22.8,65,20.51,4,High,2.47

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1500 non-null   datetime64[ns]
 1   city                   1500 non-null   object
 2   temperature_c          1500 non-null   float64
 3   humidity_percent       1500 non-null   int64
 4   electricity_units_kwh  1500 non-null   float64
 5   household_size         1500 non-null   int64
 6   income_level           1500 non-null   object
 7   power_outage_hours     1500 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(2)
memory usage: 93.9+ KB

In [10]:
df.set_index('date', inplace=True)

In [11]:
df.head(3)

,city,temperature_c,humidity_percent,electricity_units_kwh,household_size,income_level,power_outage_hours
date,,,,,,,
2022-01-01,Peshawar,26.9,88,26.65,3,Low,3.32
2022-01-02,Quetta,31.4,85,25.32,3,High,1.26
2022-01-03,Islamabad,37.5,51,23.40,7,Low,2.51

In [12]:
print(df.isnull().sum())

city                     0
temperature_c            0
humidity_percent         0
electricity_units_kwh    0
household_size           0
income_level             0
power_outage_hours       0
dtype: int64

In [13]:
print(" Before :", df.shape)
df = df.drop_duplicates()
print(" After :", df.shape)

 Before : (1500, 7)
 After : (1500, 7)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1500 entries, 2022-01-01 to 2026-02-08
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   1500 non-null   object
 1   temperature_c          1500 non-null   float64
 2   humidity_percent       1500 non-null   int64
 3   electricity_units_kwh  1500 non-null   float64
 4   household_size         1500 non-null   int64
 5   income_level           1500 non-null   object
 6   power_outage_hours     1500 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 93.8+ KB

In [15]:
# Encode categorical columns:
print(df['city'].unique())
print(df['income_level'].unique())
print(df['income_level'].value_counts())

['Peshawar' 'Quetta' 'Islamabad' 'Lahore' 'Karachi']
['Low' 'High' 'Middle']
income_level
Low       548
Middle    489
High      463
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
le_city = LabelEncoder()
le_income = LabelEncoder()

df['city'] = le_city.fit_transform(df['city'])
df['income_level'] = le_income.fit_transform(df['income_level'])

In [17]:
df.head(15)

,city,temperature_c,humidity_percent,electricity_units_kwh,household_size,income_level,power_outage_hours
date,,,,,,,
2022-01-01,3,26.9,88,26.65,3,1,3.32
2022-01-02,4,31.4,85,25.32,3,0,1.26
2022-01-03,0,37.5,51,23.40,7,1,2.51
2022-01-04,4,22.8,65,20.51,4,0,2.47
2022-01-05,4,30.9,63,29.20,7,2,0.32
2022-01-06,2,25.1,59,22.84,5,2,0.18
2022-01-07,0,38.4,54,10.20,2,1,1.92
2022-01-08,0,19.3,74,15.30,4,2,0.26
2022-01-09,0,26.1,57,20.88,6,2,2.85
2022-01-10,4,32.6,30,23.86,8,1,1.94
2022-01-11,3,41.0,78,21.66,5,2,2.77
2022-01-12,0,29.5,74,29.31,4,1,0.53
2022-01-13,4,26.1,33,10.29,8,0,0.57
2022-01-14,2,43.2,36,22.86,8,0,1.67
2022-01-15,3,19.9,78,11.09,2,0,0.05

In [18]:
print(df['income_level'].unique())

[1 0 2]

In [19]:
# sort data by using the date
df = df.sort_index()
print(df.head(4))

            city  temperature_c  humidity_percent  electricity_units_kwh  \
date
2022-01-01     3           26.9                88                  26.65
2022-01-02     4           31.4                85                  25.32
2022-01-03     0           37.5                51                  23.40
2022-01-04     4           22.8                65                  20.51

            household_size  income_level  power_outage_hours
date
2022-01-01               3             1                3.32
2022-01-02               3             0                1.26
2022-01-03               7             1                2.51
2022-01-04               4             0                2.47

In [20]:
print(df.tail(5))

            city  temperature_c  humidity_percent  electricity_units_kwh  \
date
2026-02-04     3           23.6                79                  20.20
2026-02-05     4           37.1                34                  26.85
2026-02-06     4           31.9                82                  18.49
2026-02-07     3           33.9                58                  17.50
2026-02-08     3           32.4                68                  20.67

            household_size  income_level  power_outage_hours
date
2026-02-04               3             1                1.06
2026-02-05               2             1                0.10
2026-02-06               4             2                2.69
2026-02-07               3             2                2.30
2026-02-08               6             1                0.31

In [21]:
# df.to_csv('cleaned_data.csv', index=False)

In [22]:
df.reset_index(inplace=True)

df.to_csv("cleaned_data.csv", index=False)